### ISSUE TITLE
Rename chapter files with concatenation

### ISSUE THREAD

**Issue by tarahmarie** [jdmartin/eltec-text-splitter#1]
For when using in larger text masses, and individual files are needed (e.g. sequence alignment). Otherwise, one has to manually relabel all the files in 100 different folders and move them up one. Year, name, chapter, chapter number is nice...since you already created that interface in the gutenberg splitter anyway :-)

**Comment by jdmartin** [comment]
Right-o.  Will adjust so that files follow the PG Splitter format: `year-title-chapter_n`.  Should be straightforward enough to pull that year from the publicationStmt -> sourceDesc -> date, assuming it's there.  I'll try to get on this a bit later today, once some other work is finished. :)

**Comment by jdmartin** [comment]
Should now be remedied.  Please do re-open, if something is amiss. :)

**Comment by jdmartin** [comment]
Going to add a small optimization... that intermediary folder isn't really needed, which I think you indicated.  Sorry about that.

**Comment by jdmartin** [comment]
Ok, that should do it.  As before, feel free to reopen/start a new one.  :)
